export const getPlaceFetch =
    [
        {
            id: 100,
            alt: "Oeuvre d'art du musée des Beaux-Arts",
            name: "Musée des Beaux-arts",
            short_description: "Le musée des Beaux-Arts de Rennes est un musée d'art et d'archéologie français.",
            description: "Le musée des Beaux-Arts de Rennes est un musée d'art et d'archéologie français. Il a été constitué avec, pour fonds initial, les œuvres saisies lors des confiscations révolutionnaires effectuées en 1794 dans les édifices religieux et civils de la ville de Rennes.",
            image: "https://media-cdn.tripadvisor.com/media/photo-s/0c/51/be/2a/una-delle-sale.jpg",
        },
        {
            id: 101,
            alt: "Salle d'accueil Frac Bretagne",
            name: "Frac Bretagne",
            short_description: "Frac Bretagne a pour objectif de soutenir et promouvoir la création contemporaine.",
            description: "Premier né des Fonds régionaux d’art contemporain, le Frac Bretagne a pour objectif de soutenir et promouvoir la création contemporaine, de favoriser la présence de celle-ci sur le territoire régional, et de sensibiliser le plus large public à l’art d’aujourd’hui.",
            image: "https://www.fracbretagne.fr/wp-content/uploads/2018/12/BAT_Frac-Bretagne_Photo-Roland-Halbe-REGION-BRETAGNE-1_ok.jpg",
        },
        {
            id: 100,
            alt: "Oeuvre d'art du musée des Beaux-Arts",
            name: "Musée des Beaux-arts",
            short_description: "Le musée des Beaux-Arts de Rennes est un musée d'art et d'archéologie français.",
            description: "Le musée des Beaux-Arts de Rennes est un musée d'art et d'archéologie français. Il a été constitué avec, pour fonds initial, les œuvres saisies lors des confiscations révolutionnaires effectuées en 1794 dans les édifices religieux et civils de la ville de Rennes.",
            image: "https://media-cdn.tripadvisor.com/media/photo-s/0c/51/be/2a/una-delle-sale.jpg",
        },
        {
            id: 101,
            alt: "Salle d'accueil Frac Bretagne",
            name: "Frac Bretagne",
            short_description: "Frac Bretagne a pour objectif de soutenir et promouvoir la création contemporaine.",
            description: "Premier né des Fonds régionaux d’art contemporain, le Frac Bretagne a pour objectif de soutenir et promouvoir la création contemporaine, de favoriser la présence de celle-ci sur le territoire régional, et de sensibiliser le plus large public à l’art d’aujourd’hui.",
            image: "https://www.fracbretagne.fr/wp-content/uploads/2018/12/BAT_Frac-Bretagne_Photo-Roland-Halbe-REGION-BRETAGNE-1_ok.jpg",
        },
        {
            id: 100,
            alt: "Oeuvre d'art du musée des Beaux-Arts",
            name: "Musée des Beaux-arts",
            short_description: "Le musée des Beaux-Arts de Rennes est un musée d'art et d'archéologie français.",
            description: "Le musée des Beaux-Arts de Rennes est un musée d'art et d'archéologie français. Il a été constitué avec, pour fonds initial, les œuvres saisies lors des confiscations révolutionnaires effectuées en 1794 dans les édifices religieux et civils de la ville de Rennes.",
            image: "https://media-cdn.tripadvisor.com/media/photo-s/0c/51/be/2a/una-delle-sale.jpg",
        },
        {
            id: 101,
            alt: "Salle d'accueil Frac Bretagne",
            name: "Frac Bretagne",
            short_description: "Frac Bretagne a pour objectif de soutenir et promouvoir la création contemporaine.",
            description: "Premier né des Fonds régionaux d’art contemporain, le Frac Bretagne a pour objectif de soutenir et promouvoir la création contemporaine, de favoriser la présence de celle-ci sur le territoire régional, et de sensibiliser le plus large public à l’art d’aujourd’hui.",
            image: "https://www.fracbretagne.fr/wp-content/uploads/2018/12/BAT_Frac-Bretagne_Photo-Roland-Halbe-REGION-BRETAGNE-1_ok.jpg",
        },
    ]